CREATE  SCHEMA dbex;

/*markdown
## Criando a tabela `cidades`
*/

CREATE TABLE dbex.cidades (
    id serial PRIMARY KEY,
    nome varchar(150) NOT NULL,
    estado char(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS dbex.cidades (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome varchar(150) NOT NULL,
    estado char(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS dbex.cidades (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(150) NOT NULL,
    estado char(2) NOT NULL
);

/*markdown
## Removendo a tabela `cidades`
*/

DROP TABLE dbex.cidades;

/*markdown
## Criando a tabela `localizações`
*/

CREATE TABLE IF NOT EXISTS dbex.localizacoes (
    id int GENERATED ALWAYS AS IDENTITY,
    id_cidade int NOT NULL,
    latitude int NOT NULL,
    longitude float NOT NULL,
    CONSTRAINT localizacoes_pk PRIMARY KEY (id),
    CONSTRAINT localizacoes_cidades_fk FOREIGN KEY (id_cidade) REFERENCES dbex.cidades(id)
);

/*markdown
## Criando a Tabela `tempos`
*/

CREATE TABLE IF NOT EXISTS dbex.tempos (
    id int GENERATED ALWAYS AS IDENTITY,
    id_cidade int NOT NULL,
    temp_min int NOT NULL,
    temp_max int NOT NULL,
    precip_pluviom float NULL DEFAULT '0.0',
    data_coleta TIMESTAMP NOT NULL, -- DEFAULT current_date() ver na documentação do PostgreSQL.
    CONSTRAINT tempos_pk PRIMARY KEY (id),
    CONSTRAINT tempos_cidades_fk FOREIGN KEY (id_cidade) REFERENCES dbex.cidades(id)
)

/*markdown
## Tamanho das Strings
*/

SELECT octet_lenght('IFRN'::varchar(8));

SELECT octet_lenght('IFRN Campus Natal-Central'::varchar(8));

SELECT octet_lenght(''::varchar(8));

/*markdown
#### Char - Sempre será o tamanho definido independente da quantidade de caracteres.
*/

SELECT octet_lenght('IFRN'::char(2));

SELECT octet_lenght(' '::char(2));

SELECT true='on';
SELECT true='off';
SELECT false='0';

/*markdown
## Visualizando os dados da tabela
*/

SELECT * FROM dbex.cidades;

ALTER TABLE dbex.localizacoes ALTER ...;